/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 10 17:21:14 GMT 2026
 */

package org.apache.syncope.core.spring.security;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import groovy.lang.NonEmptySequence;
import java.util.List;
import java.util.Stack;
import org.apache.syncope.core.persistence.api.dao.PasswordRule;
import org.apache.syncope.core.persistence.api.entity.Implementation;
import org.apache.syncope.core.persistence.api.entity.policy.PasswordPolicy;
import org.apache.syncope.core.persistence.api.entity.resource.ExternalResource;
import org.apache.syncope.core.spring.security.DefaultPasswordGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultPasswordGenerator_ESTest extends DefaultPasswordGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      PasswordPolicy passwordPolicy0 = mock(PasswordPolicy.class, new ViolatedAssumptionAnswer());
      doReturn((List<Implementation>) null).when(passwordPolicy0).getRules();
      // Undeclared exception!
      try { 
        defaultPasswordGenerator0.getPasswordRules(passwordPolicy0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.DefaultPasswordGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      PasswordPolicy passwordPolicy0 = mock(PasswordPolicy.class, new ViolatedAssumptionAnswer());
      PasswordPolicy passwordPolicy1 = mock(PasswordPolicy.class, new ViolatedAssumptionAnswer());
      doReturn(nonEmptySequence0).when(passwordPolicy1).getRules();
      nonEmptySequence0.add((Object) defaultPasswordGenerator0);
      ExternalResource externalResource0 = mock(ExternalResource.class, new ViolatedAssumptionAnswer());
      doReturn(passwordPolicy0, passwordPolicy1).when(externalResource0).getPasswordPolicy();
      // Undeclared exception!
      try { 
        defaultPasswordGenerator0.generate(externalResource0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.syncope.core.spring.security.DefaultPasswordGenerator cannot be cast to org.apache.syncope.core.persistence.api.entity.Implementation
         //
         verifyException("org.apache.syncope.core.spring.security.DefaultPasswordGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      // Undeclared exception!
      try { 
        defaultPasswordGenerator0.generate((List<PasswordPolicy>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.DefaultPasswordGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      nonEmptySequence0.add((Object) defaultPasswordGenerator0);
      // Undeclared exception!
      try { 
        defaultPasswordGenerator0.generate((List<PasswordPolicy>) nonEmptySequence0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.syncope.core.spring.security.DefaultPasswordGenerator cannot be cast to org.apache.syncope.core.persistence.api.entity.policy.PasswordPolicy
         //
         verifyException("java.util.ArrayList$ArrayListSpliterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      Stack<Implementation> stack0 = new Stack<Implementation>();
      stack0.setSize(3502);
      PasswordPolicy passwordPolicy0 = mock(PasswordPolicy.class, new ViolatedAssumptionAnswer());
      doReturn(stack0).when(passwordPolicy0).getRules();
      List<PasswordRule> list0 = defaultPasswordGenerator0.getPasswordRules(passwordPolicy0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      PasswordPolicy passwordPolicy0 = mock(PasswordPolicy.class, new ViolatedAssumptionAnswer());
      PasswordPolicy passwordPolicy1 = mock(PasswordPolicy.class, new ViolatedAssumptionAnswer());
      doReturn((List) null).when(passwordPolicy1).getRules();
      ExternalResource externalResource0 = mock(ExternalResource.class, new ViolatedAssumptionAnswer());
      doReturn(passwordPolicy0, passwordPolicy1).when(externalResource0).getPasswordPolicy();
      // Undeclared exception!
      try { 
        defaultPasswordGenerator0.generate(externalResource0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.spring.security.DefaultPasswordGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      ExternalResource externalResource0 = mock(ExternalResource.class, new ViolatedAssumptionAnswer());
      doReturn((PasswordPolicy) null).when(externalResource0).getPasswordPolicy();
      String string0 = defaultPasswordGenerator0.generate(externalResource0);
      assertEquals("aaaaaaaa", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DefaultPasswordGenerator defaultPasswordGenerator0 = new DefaultPasswordGenerator();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      String string0 = defaultPasswordGenerator0.generate((List<PasswordPolicy>) nonEmptySequence0);
      assertEquals("aaaaaaaa", string0);
  }
}
